### PR TITLE
Removing 'module-invalid-version-added' from sanity text since 'version' is removed,

### PR DESCRIPTION
**Pull request by pkesavap**
Created a GNU 2.0 license and updates it with (    Copyright 2014 Red Hat, Inc.)

### CODE REVIEW

**Comment by pkesavap** [comment]
This PR,
Contains,
1) LICENSE
2)Removing 'module-invalid-version-added' from sanity text since 'version' is removed

Requesting Review: @felixfontein @bmillemathias

**Comment by felixfontein** [comment]
I've looked at the CI runs for this PR, and I'm not sure you are actually running all sanity tests. If you specify `--python x.y` to `ansible-test sanity --docker -v`, you are actually **restricting** which tests are run. You should simply run `ansible-test sanity --docker -v` once for every Ansible version, without specifying any `--python x.y`, to make sure that *all* sanity tests are run. (The `--python` parameter is only important for unit and integration tests.)

**Comment by felixfontein** [comment]
(Trying to look some more, it looks like they are all running. GitHub action logs are kind of harder to search through :) You can save some CI time though by running ansible-test only once per Python version though.)

**Comment by bmillemathias** [comment]
> (Trying to look some more, it looks like they are all running. GitHub action logs are kind of harder to search through :) You can save some CI time though by running ansible-test only once per Python version though.)

done in #9

**Pull request merged**
